version: "3.8"

services:
  nginx:
    image: shan1500/multi-nginx:latest
    ports:
      - "80:80"
    depends_on:
      - client
      - server

  client:
    image: shan1500/multi-client:latest
    environment:
      - NODE_ENV=production

  server:
    image: shan1500/multi-server:latest
    environment:
      - PGUSER=postgres
      - PGPASSWORD=postgres_password
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPORT=5432
      - REDIS_HOST=redis

  worker:
    image: shan1500/multi-worker:latest
    environment:
      - PGUSER=postgres
      - PGPASSWORD=postgres_password
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPORT=5432
      - REDIS_HOST=redis

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=postgres_password

  redis:
    image: redis:alpine
