version: "3"

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - client
      - server

  client:
    build:
      context: ./client
    expose:
      - "80"  # ✅ FIXED: This must match the EXPOSE in client/Dockerfile

  server:
    build:
      context: ./server
    expose:
      - "5000"
    environment:
      - PGUSER=postgres
      - PGPASSWORD=postgres_password
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPORT=5432
      - REDIS_HOST=redis

  worker:
    build:
      context: ./worker
    environment:
      - PGUSER=postgres
      - PGPASSWORD=postgres_password
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPORT=5432
      - REDIS_HOST=redis

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=postgres_password
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine

volumes:
  pgdata:
