version: "3.8"

services:
  client:
    image: shan1500/multi-client
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production

  server:
    image: shan1500/multi-server
    environment:
      - PGUSER=postgres
      - PGPASSWORD=postgres_password
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPORT=5432
      - REDIS_HOST=redis

  worker:
    image: shan1500/multi-worker
    environment:
      - PGUSER=postgres
      - PGPASSWORD=postgres_password
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPORT=5432
      - REDIS_HOST=redis

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=postgres_password

  redis:
    image: redis:alpine
