version: "3.8"

services:
  client:
    image: yourdockerhubuser/multi-client
    environment:
      - NODE_ENV=production

  server:
    image: yourdockerhubuser/multi-server
    environment:
      - PGUSER=postgres
      - PGPASSWORD=postgres_password
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPORT=5432

  worker:
    image: yourdockerhubuser/multi-worker

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=postgres_password

  redis:
    image: redis:alpine

  nginx:
    image: yourdockerhubuser/multi-nginx
    ports:
      - "80:80"

