name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test -- --watchAll=false

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build React app
        run: npm run build

      # Add your deploy steps here, e.g., upload to Netlify, AWS, or push Docker image
      # - name: Deploy to Netlify
      #   uses: nwtgck/actions-netlify@v1.1
      #   with:
      #     publish-dir: ./build
      #     production-branch: main
      #     github-token: ${{ secrets.GITHUB_TOKEN }}