name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install server dependencies and run tests
        working-directory: ./server
        run: |
          npm ci
          npm test -- --watchAll=false

      - name: Install client dependencies and run tests
        working-directory: ./client
        run: |
          npm ci
          npm test -- --watchAll=false

      # add similar step for worker if needed

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install and build server
        working-directory: ./server
        run: |
          npm ci
          npm run build

      - name: Install and build client
        working-directory: ./client
        run: |
          npm ci
          npm run build

      # add similar step for worker if needed

      # Deployment step here...