name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install client dependencies
        working-directory: ./client
        run: npm ci

      - name: Build client
        working-directory: ./client
        run: npm run build
      
      - name: List root directory files
        run: ls -la
      
      - name: Copy Dockerrun.aws.json to build folder
        run: cp Dockerrun.aws.json ./client/build/
      
      - name: Prepare deployment bundle
        run: |
          cd ./client/build
          zip -r ../../../deploy.zip *

      - name: Prepare deployment bundle
        run: |
          cd ./client/build
          zip -r ../../../deploy.zip *
          cd ../../

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: multi-docker
          environment_name: multi-docker-env
          region: ${{ secrets.AWS_REGION }}
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip