name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List client directory files
        working-directory: ./client
        run: ls -la

      - name: Install client dependencies
        working-directory: ./client
        run: npm ci

      - name: List server directory files
        working-directory: ./server
        run: ls -la

      - name: Install server dependencies
        working-directory: ./server
        run: npm ci

      - name: List worker directory files
        working-directory: ./worker
        run: ls -la

      - name: Install worker dependencies
        working-directory: ./worker
        run: npm ci

      - name: Build client
        working-directory: ./client
        run: npm run build

      - name: Zip build artifacts
        run: zip -r deploy.zip ./client/build

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: multi-docker
          environment_name: multi-docker-env
          region: ${{ secrets.AWS_REGION }}
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip